version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pg-challenge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-password
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-challenge
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

